In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [2]:
df = pd.read_csv("./data/IMDB Dataset.csv")

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df.sample(5)

                                                  review sentiment
47165  This movie was excellent from start-to-finish....  positive
20781  The Further Adventures of Ma and Pa Kettle alm...  positive
28982  The credits come from the Sandy Frank stitchin...  negative
14595  "Gespenster" Question of to be cool in the Ger...  positive
45829  This movie has an outstanding acting, by Maril...  positive

In [5]:
df.sentiment.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
df_pos = df[df['sentiment']=='positive'][:5000]
df_neg = df[df['sentiment']=='negative'][:5000]

df_reviews = pd.concat([df_pos, df_neg ])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
train,test = train_test_split(df_reviews,test_size =0.33,random_state=42)

In [9]:
train_x, train_y = train['review'], train['sentiment']
test_x, test_y = test['review'], test['sentiment']

In [10]:
train_y.value_counts()

sentiment
negative    3378
positive    3322
Name: count, dtype: int64

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tfidf = TfidfVectorizer(stop_words='english')
train_x_vector = tfidf.fit_transform(train_x)
test_x_vector = tfidf.transform(test_x)

In [13]:
train_x.shape

(6700,)

In [14]:
train_x_vector.shape

(6700, 44107)

In [15]:
type(train_x_vector)

scipy.sparse._csr.csr_matrix

In [16]:
primera_resenia = pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out()).iloc[0]

In [17]:
primera_resenia

00           NaN
000          NaN
007          NaN
00am         NaN
00s          NaN
            ...
ísnt         NaN
île          NaN
önsjön       NaN
über         NaN
überwoman    NaN
Name: 6746, Length: 44107, dtype: Sparse[float64, nan]

In [18]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

In [19]:
primera_resenia[primera_resenia != 0]

00           NaN
000          NaN
007          NaN
00am         NaN
00s          NaN
            ...
ísnt         NaN
île          NaN
önsjön       NaN
über         NaN
überwoman    NaN
Name: 6746, Length: 44107, dtype: Sparse[float64, nan]

In [20]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

In [21]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(train_x_vector, train_y)

SVC(kernel='linear')

In [22]:
print(svc.predict(tfidf.transform(['A good movie'])))
print(svc.predict(tfidf.transform(['An excellent movie'])))
print(svc.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])))

['positive']
['positive']
['negative']

In [23]:
print(svc.score(test_x_vector, test_y))

0.8706060606060606

In [24]:
from sklearn.metrics import f1_score

f1_score(test_y,svc.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

array([0.87400413, 0.86701962])

In [25]:
from sklearn.metrics import classification_report

print(classification_report(test_y,
                            svc.predict(test_x_vector),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300

In [26]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(test_y,
                           svc.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat

array([[1481,  197],
       [ 230, 1392]])

In [27]:
conf_mat = confusion_matrix(test_y,
                           svc.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat

array([[1481,  197],
       [ 230, 1392]])

In [28]:
#logistic regression 
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000)  # a veces necesita más iteraciones
log_reg.fit(train_x_vector, train_y)

print("LogisticRegression accuracy:", log_reg.score(test_x_vector, test_y))

y_pred_lr = log_reg.predict(test_x_vector)
print("LogisticRegression F1:", 
      f1_score(test_y, y_pred_lr, labels=['positive', 'negative'], average=None))
print(classification_report(test_y, y_pred_lr, labels=['positive', 'negative']))

print("Matriz de confusión LR:")
print(confusion_matrix(test_y, y_pred_lr, labels=['positive', 'negative']))

LogisticRegression accuracy: 0.8718181818181818
LogisticRegression F1: [0.87488909 0.86859273]
              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300

Matriz de confusión LR:
[[1479  199]
 [ 224 1398]]

In [29]:
#GaussianNB 
from sklearn.naive_bayes import GaussianNB

# ¡Cuidado! Esto puede consumir bastante memoria
train_x_dense = train_x_vector.toarray()
test_x_dense = test_x_vector.toarray()

gnb = GaussianNB()
gnb.fit(train_x_dense, train_y)

print("GaussianNB accuracy:", gnb.score(test_x_dense, test_y))

y_pred_gnb = gnb.predict(test_x_dense)
print("GaussianNB F1:", 
      f1_score(test_y, y_pred_gnb, labels=['positive', 'negative'], average=None))
print(classification_report(test_y, y_pred_gnb, labels=['positive', 'negative']))

print("Matriz de confusión GNB:")
print(confusion_matrix(test_y, y_pred_gnb, labels=['positive', 'negative']))

GaussianNB accuracy: 0.6427272727272727
GaussianNB F1: [0.6366718 0.6485842]
              precision    recall  f1-score   support

    positive       0.66      0.62      0.64      1678
    negative       0.63      0.67      0.65      1622

    accuracy                           0.64      3300
   macro avg       0.64      0.64      0.64      3300
weighted avg       0.64      0.64      0.64      3300

Matriz de confusión GNB:
[[1033  645]
 [ 534 1088]]

In [30]:
#desicion clasificacion de arbol 
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42, max_depth=None)  # puedes limitar max_depth
dt.fit(train_x_vector, train_y)

print("DecisionTree accuracy:", dt.score(test_x_vector, test_y))

y_pred_dt = dt.predict(test_x_vector)
print("DecisionTree F1:", 
      f1_score(test_y, y_pred_dt, labels=['positive', 'negative'], average=None))
print(classification_report(test_y, y_pred_dt, labels=['positive', 'negative']))

print("Matriz de confusión DT:")
print(confusion_matrix(test_y, y_pred_dt, labels=['positive', 'negative']))

DecisionTree accuracy: 0.7163636363636363
DecisionTree F1: [0.71807229 0.71463415]
              precision    recall  f1-score   support

    positive       0.73      0.71      0.72      1678
    negative       0.71      0.72      0.71      1622

    accuracy                           0.72      3300
   macro avg       0.72      0.72      0.72      3300
weighted avg       0.72      0.72      0.72      3300

Matriz de confusión DT:
[[1192  486]
 [ 450 1172]]

In [ ]:
#conlusion: el mejor modelo es el SVC pero el SVM linea y logistic regression funcionan tambien muy bien y de forma casi igual, con una precision cercana al 87% y F1{ equuilibrado para reseñas positivas y negativas
#en cambio el decisiontree baja bastante alrededor del 72% de precision, lo que indica mas errores y peor generalizacion con los vectores TF-IDF de alta dimension
#gaussian es el que peor se comporta porque sus supuestos estadisticos no encajan bien con este tipo de representacion de tecto, por eso comete mas erro y no es buena opcion para este problema